package com.kingfish.show.mybatis.model;

import java.util.Date;

public class Msg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.show_id
     *
     * @mbg.generated
     */
    private Long showId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.from_user_id
     *
     * @mbg.generated
     */
    private Long fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.to_user_id
     *
     * @mbg.generated
     */
    private Long toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.parent_msg_id
     *
     * @mbg.generated
     */
    private Long parentMsgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.agree_num
     *
     * @mbg.generated
     */
    private Integer agreeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.id
     *
     * @return the value of msg.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.id
     *
     * @param id the value for msg.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.gmt_create
     *
     * @return the value of msg.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.gmt_create
     *
     * @param gmtCreate the value for msg.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.gmt_modify
     *
     * @return the value of msg.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.gmt_modify
     *
     * @param gmtModify the value for msg.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.show_id
     *
     * @return the value of msg.show_id
     *
     * @mbg.generated
     */
    public Long getShowId() {
        return showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.show_id
     *
     * @param showId the value for msg.show_id
     *
     * @mbg.generated
     */
    public void setShowId(Long showId) {
        this.showId = showId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.from_user_id
     *
     * @return the value of msg.from_user_id
     *
     * @mbg.generated
     */
    public Long getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.from_user_id
     *
     * @param fromUserId the value for msg.from_user_id
     *
     * @mbg.generated
     */
    public void setFromUserId(Long fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.to_user_id
     *
     * @return the value of msg.to_user_id
     *
     * @mbg.generated
     */
    public Long getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.to_user_id
     *
     * @param toUserId the value for msg.to_user_id
     *
     * @mbg.generated
     */
    public void setToUserId(Long toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.content
     *
     * @return the value of msg.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.content
     *
     * @param content the value for msg.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.parent_msg_id
     *
     * @return the value of msg.parent_msg_id
     *
     * @mbg.generated
     */
    public Long getParentMsgId() {
        return parentMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.parent_msg_id
     *
     * @param parentMsgId the value for msg.parent_msg_id
     *
     * @mbg.generated
     */
    public void setParentMsgId(Long parentMsgId) {
        this.parentMsgId = parentMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.agree_num
     *
     * @return the value of msg.agree_num
     *
     * @mbg.generated
     */
    public Integer getAgreeNum() {
        return agreeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.agree_num
     *
     * @param agreeNum the value for msg.agree_num
     *
     * @mbg.generated
     */
    public void setAgreeNum(Integer agreeNum) {
        this.agreeNum = agreeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.ip
     *
     * @return the value of msg.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msg.ip
     *
     * @param ip the value for msg.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}