package com.kingfish.show.mybatis.model;

import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail_url
     *
     * @mbg.generated
     */
    private String detailUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_p4p
     *
     * @mbg.generated
     */
    private Boolean isP4p;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.p4p_url
     *
     * @mbg.generated
     */
    private String p4pUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cate_id
     *
     * @mbg.generated
     */
    private Long cateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.view_sales
     *
     * @mbg.generated
     */
    private String viewSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sale_id
     *
     * @mbg.generated
     */
    private Long saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.l1_category
     *
     * @mbg.generated
     */
    private Long l1Category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.source
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.shop_url
     *
     * @mbg.generated
     */
    private String shopUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.similar_url
     *
     * @mbg.generated
     */
    private String similarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_create
     *
     * @return the value of product.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_create
     *
     * @param gmtCreate the value for product.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.gmt_modify
     *
     * @return the value of product.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.gmt_modify
     *
     * @param gmtModify the value for product.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail_url
     *
     * @return the value of product.detail_url
     *
     * @mbg.generated
     */
    public String getDetailUrl() {
        return detailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail_url
     *
     * @param detailUrl the value for product.detail_url
     *
     * @mbg.generated
     */
    public void setDetailUrl(String detailUrl) {
        this.detailUrl = detailUrl == null ? null : detailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_p4p
     *
     * @return the value of product.is_p4p
     *
     * @mbg.generated
     */
    public Boolean getIsP4p() {
        return isP4p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_p4p
     *
     * @param isP4p the value for product.is_p4p
     *
     * @mbg.generated
     */
    public void setIsP4p(Boolean isP4p) {
        this.isP4p = isP4p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.p4p_url
     *
     * @return the value of product.p4p_url
     *
     * @mbg.generated
     */
    public String getP4pUrl() {
        return p4pUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.p4p_url
     *
     * @param p4pUrl the value for product.p4p_url
     *
     * @mbg.generated
     */
    public void setP4pUrl(String p4pUrl) {
        this.p4pUrl = p4pUrl == null ? null : p4pUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cate_id
     *
     * @return the value of product.cate_id
     *
     * @mbg.generated
     */
    public Long getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cate_id
     *
     * @param cateId the value for product.cate_id
     *
     * @mbg.generated
     */
    public void setCateId(Long cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.view_sales
     *
     * @return the value of product.view_sales
     *
     * @mbg.generated
     */
    public String getViewSales() {
        return viewSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.view_sales
     *
     * @param viewSales the value for product.view_sales
     *
     * @mbg.generated
     */
    public void setViewSales(String viewSales) {
        this.viewSales = viewSales == null ? null : viewSales.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sale_id
     *
     * @return the value of product.sale_id
     *
     * @mbg.generated
     */
    public Long getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sale_id
     *
     * @param saleId the value for product.sale_id
     *
     * @mbg.generated
     */
    public void setSaleId(Long saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.l1_category
     *
     * @return the value of product.l1_category
     *
     * @mbg.generated
     */
    public Long getL1Category() {
        return l1Category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.l1_category
     *
     * @param l1Category the value for product.l1_category
     *
     * @mbg.generated
     */
    public void setL1Category(Long l1Category) {
        this.l1Category = l1Category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.source
     *
     * @return the value of product.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.source
     *
     * @param source the value for product.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pic_url
     *
     * @return the value of product.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pic_url
     *
     * @param picUrl the value for product.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.shop_url
     *
     * @return the value of product.shop_url
     *
     * @mbg.generated
     */
    public String getShopUrl() {
        return shopUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.shop_url
     *
     * @param shopUrl the value for product.shop_url
     *
     * @mbg.generated
     */
    public void setShopUrl(String shopUrl) {
        this.shopUrl = shopUrl == null ? null : shopUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.similar_url
     *
     * @return the value of product.similar_url
     *
     * @mbg.generated
     */
    public String getSimilarUrl() {
        return similarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.similar_url
     *
     * @param similarUrl the value for product.similar_url
     *
     * @mbg.generated
     */
    public void setSimilarUrl(String similarUrl) {
        this.similarUrl = similarUrl == null ? null : similarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.title
     *
     * @return the value of product.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.title
     *
     * @param title the value for product.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.keyword
     *
     * @return the value of product.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.keyword
     *
     * @param keyword the value for product.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }
}