package com.kingfish.show.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShowsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shows
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shows
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shows
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public ShowsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shows
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNull() {
            addCriterion("gmt_modify is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNotNull() {
            addCriterion("gmt_modify is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyEqualTo(Date value) {
            addCriterion("gmt_modify =", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotEqualTo(Date value) {
            addCriterion("gmt_modify <>", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThan(Date value) {
            addCriterion("gmt_modify >", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modify >=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThan(Date value) {
            addCriterion("gmt_modify <", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modify <=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIn(List<Date> values) {
            addCriterion("gmt_modify in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotIn(List<Date> values) {
            addCriterion("gmt_modify not in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyBetween(Date value1, Date value2) {
            addCriterion("gmt_modify between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modify not between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTruthIsNull() {
            addCriterion("truth is null");
            return (Criteria) this;
        }

        public Criteria andTruthIsNotNull() {
            addCriterion("truth is not null");
            return (Criteria) this;
        }

        public Criteria andTruthEqualTo(Double value) {
            addCriterion("truth =", value, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthNotEqualTo(Double value) {
            addCriterion("truth <>", value, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthGreaterThan(Double value) {
            addCriterion("truth >", value, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthGreaterThanOrEqualTo(Double value) {
            addCriterion("truth >=", value, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthLessThan(Double value) {
            addCriterion("truth <", value, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthLessThanOrEqualTo(Double value) {
            addCriterion("truth <=", value, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthIn(List<Double> values) {
            addCriterion("truth in", values, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthNotIn(List<Double> values) {
            addCriterion("truth not in", values, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthBetween(Double value1, Double value2) {
            addCriterion("truth between", value1, value2, "truth");
            return (Criteria) this;
        }

        public Criteria andTruthNotBetween(Double value1, Double value2) {
            addCriterion("truth not between", value1, value2, "truth");
            return (Criteria) this;
        }

        public Criteria andPraiseIsNull() {
            addCriterion("praise is null");
            return (Criteria) this;
        }

        public Criteria andPraiseIsNotNull() {
            addCriterion("praise is not null");
            return (Criteria) this;
        }

        public Criteria andPraiseEqualTo(Integer value) {
            addCriterion("praise =", value, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseNotEqualTo(Integer value) {
            addCriterion("praise <>", value, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseGreaterThan(Integer value) {
            addCriterion("praise >", value, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseGreaterThanOrEqualTo(Integer value) {
            addCriterion("praise >=", value, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseLessThan(Integer value) {
            addCriterion("praise <", value, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseLessThanOrEqualTo(Integer value) {
            addCriterion("praise <=", value, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseIn(List<Integer> values) {
            addCriterion("praise in", values, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseNotIn(List<Integer> values) {
            addCriterion("praise not in", values, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseBetween(Integer value1, Integer value2) {
            addCriterion("praise between", value1, value2, "praise");
            return (Criteria) this;
        }

        public Criteria andPraiseNotBetween(Integer value1, Integer value2) {
            addCriterion("praise not between", value1, value2, "praise");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andPicsIsNull() {
            addCriterion("pics is null");
            return (Criteria) this;
        }

        public Criteria andPicsIsNotNull() {
            addCriterion("pics is not null");
            return (Criteria) this;
        }

        public Criteria andPicsEqualTo(String value) {
            addCriterion("pics =", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsNotEqualTo(String value) {
            addCriterion("pics <>", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsGreaterThan(String value) {
            addCriterion("pics >", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsGreaterThanOrEqualTo(String value) {
            addCriterion("pics >=", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsLessThan(String value) {
            addCriterion("pics <", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsLessThanOrEqualTo(String value) {
            addCriterion("pics <=", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsLike(String value) {
            addCriterion("pics like", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsNotLike(String value) {
            addCriterion("pics not like", value, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsIn(List<String> values) {
            addCriterion("pics in", values, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsNotIn(List<String> values) {
            addCriterion("pics not in", values, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsBetween(String value1, String value2) {
            addCriterion("pics between", value1, value2, "pics");
            return (Criteria) this;
        }

        public Criteria andPicsNotBetween(String value1, String value2) {
            addCriterion("pics not between", value1, value2, "pics");
            return (Criteria) this;
        }

        public Criteria andShowTimeIsNull() {
            addCriterion("show_time is null");
            return (Criteria) this;
        }

        public Criteria andShowTimeIsNotNull() {
            addCriterion("show_time is not null");
            return (Criteria) this;
        }

        public Criteria andShowTimeEqualTo(Date value) {
            addCriterion("show_time =", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotEqualTo(Date value) {
            addCriterion("show_time <>", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeGreaterThan(Date value) {
            addCriterion("show_time >", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("show_time >=", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeLessThan(Date value) {
            addCriterion("show_time <", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeLessThanOrEqualTo(Date value) {
            addCriterion("show_time <=", value, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeIn(List<Date> values) {
            addCriterion("show_time in", values, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotIn(List<Date> values) {
            addCriterion("show_time not in", values, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeBetween(Date value1, Date value2) {
            addCriterion("show_time between", value1, value2, "showTime");
            return (Criteria) this;
        }

        public Criteria andShowTimeNotBetween(Date value1, Date value2) {
            addCriterion("show_time not between", value1, value2, "showTime");
            return (Criteria) this;
        }

        public Criteria andIsOutsideIsNull() {
            addCriterion("is_outside is null");
            return (Criteria) this;
        }

        public Criteria andIsOutsideIsNotNull() {
            addCriterion("is_outside is not null");
            return (Criteria) this;
        }

        public Criteria andIsOutsideEqualTo(Boolean value) {
            addCriterion("is_outside =", value, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideNotEqualTo(Boolean value) {
            addCriterion("is_outside <>", value, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideGreaterThan(Boolean value) {
            addCriterion("is_outside >", value, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_outside >=", value, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideLessThan(Boolean value) {
            addCriterion("is_outside <", value, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideLessThanOrEqualTo(Boolean value) {
            addCriterion("is_outside <=", value, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideIn(List<Boolean> values) {
            addCriterion("is_outside in", values, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideNotIn(List<Boolean> values) {
            addCriterion("is_outside not in", values, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideBetween(Boolean value1, Boolean value2) {
            addCriterion("is_outside between", value1, value2, "isOutside");
            return (Criteria) this;
        }

        public Criteria andIsOutsideNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_outside not between", value1, value2, "isOutside");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicIsNull() {
            addCriterion("outside_user_head_pic is null");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicIsNotNull() {
            addCriterion("outside_user_head_pic is not null");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicEqualTo(String value) {
            addCriterion("outside_user_head_pic =", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicNotEqualTo(String value) {
            addCriterion("outside_user_head_pic <>", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicGreaterThan(String value) {
            addCriterion("outside_user_head_pic >", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicGreaterThanOrEqualTo(String value) {
            addCriterion("outside_user_head_pic >=", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicLessThan(String value) {
            addCriterion("outside_user_head_pic <", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicLessThanOrEqualTo(String value) {
            addCriterion("outside_user_head_pic <=", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicLike(String value) {
            addCriterion("outside_user_head_pic like", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicNotLike(String value) {
            addCriterion("outside_user_head_pic not like", value, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicIn(List<String> values) {
            addCriterion("outside_user_head_pic in", values, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicNotIn(List<String> values) {
            addCriterion("outside_user_head_pic not in", values, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicBetween(String value1, String value2) {
            addCriterion("outside_user_head_pic between", value1, value2, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserHeadPicNotBetween(String value1, String value2) {
            addCriterion("outside_user_head_pic not between", value1, value2, "outsideUserHeadPic");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameIsNull() {
            addCriterion("outside_user_nickname is null");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameIsNotNull() {
            addCriterion("outside_user_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameEqualTo(String value) {
            addCriterion("outside_user_nickname =", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameNotEqualTo(String value) {
            addCriterion("outside_user_nickname <>", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameGreaterThan(String value) {
            addCriterion("outside_user_nickname >", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("outside_user_nickname >=", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameLessThan(String value) {
            addCriterion("outside_user_nickname <", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameLessThanOrEqualTo(String value) {
            addCriterion("outside_user_nickname <=", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameLike(String value) {
            addCriterion("outside_user_nickname like", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameNotLike(String value) {
            addCriterion("outside_user_nickname not like", value, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameIn(List<String> values) {
            addCriterion("outside_user_nickname in", values, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameNotIn(List<String> values) {
            addCriterion("outside_user_nickname not in", values, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameBetween(String value1, String value2) {
            addCriterion("outside_user_nickname between", value1, value2, "outsideUserNickname");
            return (Criteria) this;
        }

        public Criteria andOutsideUserNicknameNotBetween(String value1, String value2) {
            addCriterion("outside_user_nickname not between", value1, value2, "outsideUserNickname");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shows
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shows
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}