package com.kingfish.show.mybatis.model;

import java.util.Date;

public class Shows {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.truth
     *
     * @mbg.generated
     */
    private Double truth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.praise
     *
     * @mbg.generated
     */
    private Integer praise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.pics
     *
     * @mbg.generated
     */
    private String pics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.show_time
     *
     * @mbg.generated
     */
    private Date showTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.is_outside
     *
     * @mbg.generated
     */
    private Boolean isOutside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.outside_user_head_pic
     *
     * @mbg.generated
     */
    private String outsideUserHeadPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shows.outside_user_nickname
     *
     * @mbg.generated
     */
    private String outsideUserNickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.id
     *
     * @return the value of shows.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.id
     *
     * @param id the value for shows.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.gmt_create
     *
     * @return the value of shows.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.gmt_create
     *
     * @param gmtCreate the value for shows.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.gmt_modify
     *
     * @return the value of shows.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.gmt_modify
     *
     * @param gmtModify the value for shows.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.content
     *
     * @return the value of shows.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.content
     *
     * @param content the value for shows.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.truth
     *
     * @return the value of shows.truth
     *
     * @mbg.generated
     */
    public Double getTruth() {
        return truth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.truth
     *
     * @param truth the value for shows.truth
     *
     * @mbg.generated
     */
    public void setTruth(Double truth) {
        this.truth = truth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.praise
     *
     * @return the value of shows.praise
     *
     * @mbg.generated
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.praise
     *
     * @param praise the value for shows.praise
     *
     * @mbg.generated
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.product_id
     *
     * @return the value of shows.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.product_id
     *
     * @param productId the value for shows.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.pics
     *
     * @return the value of shows.pics
     *
     * @mbg.generated
     */
    public String getPics() {
        return pics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.pics
     *
     * @param pics the value for shows.pics
     *
     * @mbg.generated
     */
    public void setPics(String pics) {
        this.pics = pics == null ? null : pics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.show_time
     *
     * @return the value of shows.show_time
     *
     * @mbg.generated
     */
    public Date getShowTime() {
        return showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.show_time
     *
     * @param showTime the value for shows.show_time
     *
     * @mbg.generated
     */
    public void setShowTime(Date showTime) {
        this.showTime = showTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.is_outside
     *
     * @return the value of shows.is_outside
     *
     * @mbg.generated
     */
    public Boolean getIsOutside() {
        return isOutside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.is_outside
     *
     * @param isOutside the value for shows.is_outside
     *
     * @mbg.generated
     */
    public void setIsOutside(Boolean isOutside) {
        this.isOutside = isOutside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.outside_user_head_pic
     *
     * @return the value of shows.outside_user_head_pic
     *
     * @mbg.generated
     */
    public String getOutsideUserHeadPic() {
        return outsideUserHeadPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.outside_user_head_pic
     *
     * @param outsideUserHeadPic the value for shows.outside_user_head_pic
     *
     * @mbg.generated
     */
    public void setOutsideUserHeadPic(String outsideUserHeadPic) {
        this.outsideUserHeadPic = outsideUserHeadPic == null ? null : outsideUserHeadPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shows.outside_user_nickname
     *
     * @return the value of shows.outside_user_nickname
     *
     * @mbg.generated
     */
    public String getOutsideUserNickname() {
        return outsideUserNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shows.outside_user_nickname
     *
     * @param outsideUserNickname the value for shows.outside_user_nickname
     *
     * @mbg.generated
     */
    public void setOutsideUserNickname(String outsideUserNickname) {
        this.outsideUserNickname = outsideUserNickname == null ? null : outsideUserNickname.trim();
    }
}