package com.kingfish.show.mybatis.dao;

import com.kingfish.show.mybatis.model.Shows;
import com.kingfish.show.mybatis.model.ShowsExample.Criteria;
import com.kingfish.show.mybatis.model.ShowsExample.Criterion;
import com.kingfish.show.mybatis.model.ShowsExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ShowsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String countByExample(ShowsExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("shows");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String deleteByExample(ShowsExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("shows");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String insertSelective(Shows record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("shows");
        
        if (record.getGmtCreate() != null) {
            sql.VALUES("gmt_create", "#{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModify() != null) {
            sql.VALUES("gmt_modify", "#{gmtModify,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            sql.VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getTruth() != null) {
            sql.VALUES("truth", "#{truth,jdbcType=DOUBLE}");
        }
        
        if (record.getPraise() != null) {
            sql.VALUES("praise", "#{praise,jdbcType=INTEGER}");
        }
        
        if (record.getProductId() != null) {
            sql.VALUES("product_id", "#{productId,jdbcType=BIGINT}");
        }
        
        if (record.getPics() != null) {
            sql.VALUES("pics", "#{pics,jdbcType=VARCHAR}");
        }
        
        if (record.getShowTime() != null) {
            sql.VALUES("show_time", "#{showTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsOutside() != null) {
            sql.VALUES("is_outside", "#{isOutside,jdbcType=BIT}");
        }
        
        if (record.getOutsideUserHeadPic() != null) {
            sql.VALUES("outside_user_head_pic", "#{outsideUserHeadPic,jdbcType=VARCHAR}");
        }
        
        if (record.getOutsideUserNickname() != null) {
            sql.VALUES("outside_user_nickname", "#{outsideUserNickname,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String selectByExample(ShowsExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("gmt_create");
        sql.SELECT("gmt_modify");
        sql.SELECT("content");
        sql.SELECT("truth");
        sql.SELECT("praise");
        sql.SELECT("product_id");
        sql.SELECT("pics");
        sql.SELECT("show_time");
        sql.SELECT("is_outside");
        sql.SELECT("outside_user_head_pic");
        sql.SELECT("outside_user_nickname");
        sql.FROM("shows");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Shows record = (Shows) parameter.get("record");
        ShowsExample example = (ShowsExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("shows");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModify() != null) {
            sql.SET("gmt_modify = #{record.gmtModify,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{record.content,jdbcType=VARCHAR}");
        }
        
        if (record.getTruth() != null) {
            sql.SET("truth = #{record.truth,jdbcType=DOUBLE}");
        }
        
        if (record.getPraise() != null) {
            sql.SET("praise = #{record.praise,jdbcType=INTEGER}");
        }
        
        if (record.getProductId() != null) {
            sql.SET("product_id = #{record.productId,jdbcType=BIGINT}");
        }
        
        if (record.getPics() != null) {
            sql.SET("pics = #{record.pics,jdbcType=VARCHAR}");
        }
        
        if (record.getShowTime() != null) {
            sql.SET("show_time = #{record.showTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsOutside() != null) {
            sql.SET("is_outside = #{record.isOutside,jdbcType=BIT}");
        }
        
        if (record.getOutsideUserHeadPic() != null) {
            sql.SET("outside_user_head_pic = #{record.outsideUserHeadPic,jdbcType=VARCHAR}");
        }
        
        if (record.getOutsideUserNickname() != null) {
            sql.SET("outside_user_nickname = #{record.outsideUserNickname,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("shows");
        
        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("gmt_create = #{record.gmtCreate,jdbcType=TIMESTAMP}");
        sql.SET("gmt_modify = #{record.gmtModify,jdbcType=TIMESTAMP}");
        sql.SET("content = #{record.content,jdbcType=VARCHAR}");
        sql.SET("truth = #{record.truth,jdbcType=DOUBLE}");
        sql.SET("praise = #{record.praise,jdbcType=INTEGER}");
        sql.SET("product_id = #{record.productId,jdbcType=BIGINT}");
        sql.SET("pics = #{record.pics,jdbcType=VARCHAR}");
        sql.SET("show_time = #{record.showTime,jdbcType=TIMESTAMP}");
        sql.SET("is_outside = #{record.isOutside,jdbcType=BIT}");
        sql.SET("outside_user_head_pic = #{record.outsideUserHeadPic,jdbcType=VARCHAR}");
        sql.SET("outside_user_nickname = #{record.outsideUserNickname,jdbcType=VARCHAR}");
        
        ShowsExample example = (ShowsExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Shows record) {
        SQL sql = new SQL();
        sql.UPDATE("shows");
        
        if (record.getGmtCreate() != null) {
            sql.SET("gmt_create = #{gmtCreate,jdbcType=TIMESTAMP}");
        }
        
        if (record.getGmtModify() != null) {
            sql.SET("gmt_modify = #{gmtModify,jdbcType=TIMESTAMP}");
        }
        
        if (record.getContent() != null) {
            sql.SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getTruth() != null) {
            sql.SET("truth = #{truth,jdbcType=DOUBLE}");
        }
        
        if (record.getPraise() != null) {
            sql.SET("praise = #{praise,jdbcType=INTEGER}");
        }
        
        if (record.getProductId() != null) {
            sql.SET("product_id = #{productId,jdbcType=BIGINT}");
        }
        
        if (record.getPics() != null) {
            sql.SET("pics = #{pics,jdbcType=VARCHAR}");
        }
        
        if (record.getShowTime() != null) {
            sql.SET("show_time = #{showTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsOutside() != null) {
            sql.SET("is_outside = #{isOutside,jdbcType=BIT}");
        }
        
        if (record.getOutsideUserHeadPic() != null) {
            sql.SET("outside_user_head_pic = #{outsideUserHeadPic,jdbcType=VARCHAR}");
        }
        
        if (record.getOutsideUserNickname() != null) {
            sql.SET("outside_user_nickname = #{outsideUserNickname,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shows
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, ShowsExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}